### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [DerekBird/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [2/3] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [2/3] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [2/3] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [2/3] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [2/3] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

Hey Derek! Good job on your assessment. You are super close, but we want to make sure you understand the difference between what the programming concept of `class` is referring to and an actual class that is taken at school. Because both of your examples were examples of classes one would take in school, it's hard to tell whether you're misinterpreting the meaning of class as a programming concept. To be clear, both of your examples work, but we want to see you model something other than a class that could be taught in a school. We want you to add to your assessment by thinking of a class that you would find in a furniture store. Create the class file named `class_3.txt` with a proper class name and add attributes and methods to the class the same way you did for the previous files. Add and commit these changes with a properly formatted commit message. Remember to capitalize the first word and use the present tense of the verb you start your message with. Create a file named class_3_example_object.txt and make sure this example represents an instance of whatever you chose to model in the furniture store. Give the attributes you came up with in your class values and show us what the methods return the same way you had previously. Add and commit this file with a properly formatted commit message. Push your changes to Github. Send us a message when you've made these changes, so we can review and provide feedback. Thanks Derek! 

### Assessment Results
- [] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
